### ISSUE TITLE
Specific Requests for the Main Bar

### ISSUE THREAD

**Issue by ajjimenez** [ajjimenez/Octo-Bar#1]
Here's where I'll keep track of specific liquor requests and whether or not I've brought it in:  

J Dusi Zinfandels - In Stock

Hibiki 12 - in stock
Hibiki 17 - Coming in September!
Nikka Taketsuru 12 - restocking

Tempus Fugit Kina L'avion D'or - In Stock
Bruichladdich - Classic, Islay Barley, 21 year old Signatory Bottling in stock

**Comment by azimman** [comment]
Got a few bottle requests:

[Cut Spike](http://www.klwines.com/detail.asp?sku=1172353)
[Greenore](https://www.thewhiskyexchange.com/P-2859.aspx)
[The Glenrothes 2001](http://www.klwines.com/detail.asp?sku=1144322)
[Mezcal Vago Ensamble del Barro](http://www.klwines.com/detail.asp?sku=1151720)

**Comment by ajjimenez** [comment]
I will put the Cut Spike in the Exec this afternoon.  Beware though, it's the last bottle of batch #1, and it might be a while before I can get any more.  

The rest are on their way!

**Comment by ajjimenez** [comment]
All requests thus far have now been fulfilled.

**Comment by nuclearsandwich** [comment]
@ajjimenez would it be possible to use one of the taps downstairs for cold brew coffee now that we're entering the slightly warmer and sunnier months of San Francisco?

**Comment by ajjimenez** [comment]
@nuclearsandwich Sounds like a fun idea!  Please help me if you have a better way, but as I understand it, to do it, we would need a nitro setup similar what we would have if we had Guinness on tap?  (nitro tank & regulator, stout faucet, mixed beer gas).  Also were you thinking of us making our own cold brew, or seeing if we can bring in kegs of cold brew from coffee roasters?

**Comment by nuclearsandwich** [comment]
You can do cold brew with a regular CO2 tap at a lower pressure than you'd use for fizzy drinks but we have the desire to do a nitro setup I could see that being fun too. I know [Jittery Johns](http://jitteryjohns.com/) has cold brew on tap at a number of places around the bay area but I'm not sure how to source kegs from them.

**Comment by brianmario** [comment]
fwiw I've heard stumptown provides kegs (and a nitro setup?) for their cold brew for people who want to serve it. Not sure how true it is, but a place down here in the Paso area has it and someone told me that's how they got it.

**Comment by ajjimenez** [comment]
@nuclearsandwich @brianmario  Getting closer...also a quick question, any idea how quickly the office might go through a pony keg (7.75 gal)?

**Comment by brianmario** [comment]
Seems like it would last a while - especially if it's down on the first floor and most people don't go there for their coffee in the mornings? I really have no idea on an actual guess of time though :P

**Comment by nuclearsandwich** [comment]
@ajjimenez hilariously I bet it will depend a lot on how many days I'm in HQ. I drink four to five pints a day when it flows freely. :grin: But my guess is that once it's known that will last just over a week. The cafe whose kegerator inspired me uses a 5 gallon keg and goes through it in about two days.

**Comment by ajjimenez** [comment]
@nuclearsandwich Perfect, I'll go with the conservative estimate of 1 week.  If you happen to guzzle it down, I'll adjust accordingly.

**Comment by ajjimenez** [comment]
@danishkhan The washi has landed.  please don't let Aurthur repeat the mistakes of the past!

**Comment by ajjimenez** [comment]
@nuclearsandwich the odyssey continues.  Would you have some time next week to meet with me and Tony Serrano of Highwire coffee?  We've been hammering out the technical details, but I think it would be good to have the voice of someone who would actually drink it on a regular basis.  Also, it sounds like they have a number of possible options, so it might be good to figure out what really would work best.

If you're around next week, just shoot me some open time slots and I'll coordinate.

**Comment by nuclearsandwich** [comment]
Tony goddamn Serrano! Shake his hand for me. I'm in Raleigh, NC for the next few months and no longer working out of HQ regularly. I could talk through stuff via skype or bluejeans, for coffee but wouldn't be a regular drinker.

I can nominate a few folks though if you'd like someone actually present.

_edit_ He won't know me by the name I use here. He would know me as Steven! from Barefoot though.

**Comment by ajjimenez** [comment]
Will do.  I'm definitely open to other folks going in your stead...let me know who might be available next week.

**Comment by nuclearsandwich** [comment]
@jgreet or @dreww would be good candidates if they have time. @shanaz also drinks cold brew.

**Comment by danishkhan** [comment]
@ajjimenez :sparkling_heart: thank you good sir!

**Comment by ajjimenez** [comment]
@jgreet, @dreww, @shanaz I've set a meeting with Tony Monday, 6/22 at 11AM.  Please come if any of you are available.  We'll be at the main bar.

**Comment by dreww** [comment]
i am down! highwire rules.

**Comment by ajjimenez** [comment]
Perfect.  Thanks!

**Comment by ajjimenez** [comment]
Just a heads up...we're down to the last 3 cases of GitHub's private barrel of Rusty Blade Gin.  Once it's gone, I don't plan on bringing it back unless it's specifically requested.  In other words, it may come back from time to time, but I don't think I can keep it as a bar staple unless the company explicitly calls for it.

Also, if you happen to be the sentimental type, I've got bottle #9-#14 tucked away.  I can let you know where to find it if you want to add it to the archive.

**Comment by ajjimenez** [comment]
Something new to try at the bar:  It's a Cascara (coffee cherry) soda from Tony at Highwire.  Something new that they want specific feedback on.  In addition to the coffee cherries, it also has Hibiscus and is sweetened with vanilla simple syrup.  

This should be the first of a few experimental kegs, so if anyone tries it...do let me know what you think of it.

**Comment by dreww** [comment]
whoa, awesome! thanks!

**Comment by ajjimenez** [comment]
So...that took just a bit longer than I thought it would, but we finally have cold brew coffee on tap at the bar.  Try it out, give feedback, and we'll see where it goes from here.

![img_0077](https://cloud.githubusercontent.com/assets/3975938/9054411/dd19a620-3a35-11e5-8de3-22f21dc44fa6.JPG)

**Comment by nuclearsandwich** [comment]
yessssss

**Comment by brookienoodle** [comment]
@ajjimenez the cold brew is great, and I like the soda as well, although I'll need to try it a few more times to provide more specific feedback :wink: .  How often do you come to HQ? I'd love to chat with you when you're here, I'm so curious about your gig. Btw, :heart: Rusty Blade :heart: so much, I'm sad it's a short timer.

**Comment by ajjimenez** [comment]
@brookienoodle Thanks for the feedback, seems like the cold brew's a solid winner.  I'm at HQ pretty infrequently, typically once a week to restock/check on the bar and kitchen.  If the events schedule calls for it, I'm there on an as-needed basis.  I'll definitely give you a holler once I know when I'll be in next.

**Comment by brookienoodle** [comment]
Cool, thanks @ajjimenez! Looking forward to meeting you!

**Comment by ajjimenez** [comment]
@nuclearsandwich, Tried the coffee, and definitely agree with you...tried the fresh keg, same thing.  Flushed the system clean, and while it helped a little, the tinny note still remains.  Could you try it again tonight/tomorrow and let me know if it's made any improvement?  If not, I'll pass along the note to Tony.

@brookienoodle I should be around tomorrow starting at 4PM for the Girl Geek Dinner.  Will you be around?

**Comment by dreww** [comment]
the 2nd keg (not sure what we're on right now) definitely tasted like it was a significantly deeper extraction than the first one, i noticed at the time but considered it within nominal parameters

**Comment by brookienoodle** [comment]
@ajjimenez hey AJ, I'm catching the early train today so I'll miss you. Thanks for pinging me! Let's sync up the next time you're in. :beer:

**Comment by ajjimenez** [comment]
Just tapped Duchesse De Bourgogne and it's super tasty if you're into the style...Enjoy it while it's there!

**Comment by nuclearsandwich** [comment]
oooh thass a good one!

**Comment by brookienoodle** [comment]
Oh wowza that's different. I wasn't prepared for such a shift in taste
post- hoppy ale so I didn't go for it. I will try again though, because my
palate likes that profile. :sparkle:

**Comment by ajjimenez** [comment]
Getting back to the idea of cocktail classes, I was chatting with one of my bartenders and he had a great idea for a class...Basically, the next time GitHub has an internal event/party for itself, we could hold a brief class before the party to get the essentials down...then have Hubbers rotate behind the bar making drinks at full speed.  I think it'd be a pretty great way to have hubbers really learn how to make drinks and really get to know the home bar.

**Comment by ajjimenez** [comment]
I recently re-uped the exec lounge.  There are some fun things in there at the moment, but make them last as some of the bottles are definitely once-a-year-if-at-all.

**Comment by ajjimenez** [comment]
@danishkhan @achiu ahem.
![img_8396](https://cloud.githubusercontent.com/assets/3975938/18221674/803b961e-7136-11e6-8475-5ae88aca5965.JPG)
