### ISSUE TITLE
Mescal for mixing in le bar

### ISSUE THREAD

**Issue by brianmario** [ajjimenez/Octo-Bar#2]
So we ended up finding some but am curious if there's another one we can try that has a little more smokey flavor (for mixing).

We just chatted about this but I'll open this anyway just so it's logged :)

**Comment by ajjimenez** [comment]
I've just ordered some Fidencio Classic...I think it should fit the bill nicely.  I'll holler once it's in!

**Comment by brianmario** [comment]
Nice! Thanks dude

**Comment by ajjimenez** [comment]
The Fidencio's up at the bar...I also brought in some Don Amado Rustico, which should be a great sipper.  Let me know what you make with it!
