### ISSUE TITLE
Speakeasy

### ISSUE THREAD

**Issue by ajjimenez** [ajjimenez/Octo-Bar#3]
Things for the speakeasy:
1. it's own set of bitters -done
2. sugar 
3. ice

Liquor:
More Willett - done
Bulleit - done

**Comment by azimman** [comment]
@ajjimenez would it be possible to get a porter or lager on tap in the speakeasy?

**Comment by ajjimenez** [comment]
Certainly, I'll holler once it's in.

**Comment by ajjimenez** [comment]
@azimman I haven't had a chance to verify, since I seem to want to check while there's some kind of meeting going on, but there should be a keg of Anchor Cali Lager in the speakeasy now.

**Comment by azimman** [comment]
@ajjimenez there was a couple weeks ago... have not checked to see if it needs replacing this week... yet.
